=== M-Aly/JavaChatApp/Chat/Xml/src/main/resources/com/jets/message/message.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="Session" type="SessionType"/>
    <xs:complexType name="SessionType">
        <xs:sequence>
            <xs:element name="Header" type="xs:string"/>
            <xs:element name="Msg" type="MsgContent" maxOccurs = "unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="MsgContent">
        <xs:sequence>
            <xs:element name="from" type= "xs:string"/>
            <xs:element name="to" type="xs:string" maxOccurs = "unbounded" />
            <xs:element name="date" type="xs:date"/>
            <xs:element name="body" type="xs:string"/>
            <xs:element type="xs:string" name="fontStyle" minOccurs="0"/>
            <xs:element type="xs:string" name="fontColor" minOccurs="0"/>
            <xs:element type="xs:string" name="textBackground" minOccurs="0"/>
            <xs:element type="xs:string" name="fontSize" minOccurs="0"/>
            <xs:element type="xs:boolean" name="bold" minOccurs="0"/>
            <xs:element type="xs:boolean" name="italic" minOccurs="0"/>
            <xs:element type="xs:boolean" name="Underline" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== M-Aly/JavaChatApp/Chat/Tests/src/main/java/com/jets/tests/xml/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<Session
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="message.xsd">
  <Header>Header</Header>
  <Msg>
    <from>Zainab</from>
    <to>Mayadaa</to>
    <to>Noran</to>
    <date>2001-01-01</date>
    <body>Chatting Coversation</body>
	<fontStyle> Arial </fontStyle>
    	<fontColor> Red </fontColor>
    	<textBackground> Red</textBackground>
    	<fontSize>23</fontSize>
    	<bold> true</bold>
    	<italic> true</italic>
    	<Underline>false </Underline>
  </Msg>

  <Msg>
    <from>Zainab</from>
    <to>Mayadaa</to>
    <to>Noran</to>
    <date>2001-01-01</date>
    <body>body</body>

  </Msg>
</Session>
